name: "Create Release Numbers"
description: "Creates the current release number based on checked out code"
outputs:
  version-code:
    description: "The numeric app version"
    value: ${{ steps.version-generator.outputs.version-code }}
  version:
    description: "The app version"
    value: ${{ steps.version-generator.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Set Build Number
      id: version-generator
      shell: bash
      run: |
        ./gradlew versionFile --no-configuration-cache
        VC=`date +%Y%m%d%H%M`
        echo Version Code $VC
        echo "version-code=$VC" >> $GITHUB_OUTPUT
        VERSION=`cat version.txt`
        echo Version $VERSION
        echo "version=$VERSION" >> $GITHUB_OUTPUT
